# Generated by Django 6.0.7 on 2026-08-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('panellinies', 'ΠΑΝΕΛΛΑΔΙΚΕΣ ΕΞΕΤΑΣΕΙΣ'), ('askiseis', 'ΕΠΑΓΓΕΛΜΑΤΙΚΑ ΛΥΚΕΙΑ'), ('ebooks', 'ΒΙΒΛΙΑ ΕΠΑΛ'), ('xrisima', 'ΣΧΟΛΕΣ ΕΠΑΓΓΕΛΜΑΤΙΚΗΣ ΚΑΤΑΡΤΙΣΗΣ'), ('tritovathmia', 'ΤΡΙΤΟΒΑΘΜΙΑ ΕΚΠΑΙΔΕΥΣΗ')], help_text='Σε ποιο μενού της ιστοσελίδας ανήκει η κατηγορία.', max_length=20, verbose_name='Ενότητα'),
        ),
    ]
