# Generated by Django 6.0.7 on 2026-08-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_category_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('panellinies', 'Πανελλαδικές εξετάσεις'), ('ebooks', 'Βιβλία ΕΠΑΛ'), ('askiseis', 'Επαγγελματικά λύκεια'), ('xrisima', 'Σχολές επαγγελματικής κατάρτισης'), ('tritovathmia', 'Τριτοβάθμια εκπαίδευση')], help_text='Σε ποιο μενού της ιστοσελίδας ανήκει η κατηγορία.', max_length=20, verbose_name='Ενότητα'),
        ),
    ]
