# Generated by Django 6.0.7 on 2026-08-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_category_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Τίτλος')),
                ('url', models.URLField(max_length=500, verbose_name='Σύνδεσμος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ορατός')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.category', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name': 'Σύνδεσμος',
                'verbose_name_plural': 'Σύνδεσμοι',
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('category', 'url'), name='unique_link_per_category')],
            },
        ),
    ]
