# Generated by Django 6.0.7 on 2026-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Προαιρετικό κείμενο που εμφανίζεται πάνω από το υλικό — π.χ. ο κατάλογος μαθημάτων ή μια υποχρεωτική αναφορά πηγής.', verbose_name='Κείμενο κατηγορίας'),
        ),
    ]
