# Generated by Django 6.0.7 on 2026-07-15 16:42

import content.storage
import content.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Περιεχόμενο')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='Εικόνα')),
                ('published', models.BooleanField(default=True, verbose_name='Δημοσιευμένη')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημ/νία ενημέρωσης')),
            ],
            options={
                'verbose_name': 'Ανακοίνωση',
                'verbose_name_plural': 'Ανακοινώσεις',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Όνομα')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία')),
                ('is_read', models.BooleanField(default=False, verbose_name='Αναγνωσμένο')),
            ],
            options={
                'verbose_name': 'Μήνυμα επικοινωνίας',
                'verbose_name_plural': 'Μηνύματα επικοινωνίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Όνομα')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=170, unique=True, verbose_name='Slug')),
                ('section', models.CharField(choices=[('panellinies', 'Πανελλαδικές εξετάσεις'), ('askiseis', 'Ασκήσεις – Εργασίες'), ('ebooks', 'Βιβλία (e-books)'), ('xrisima', 'Χρήσιμα')], help_text='Σε ποιο μενού της ιστοσελίδας ανήκει η κατηγορία.', max_length=20, verbose_name='Ενότητα')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('parent', models.ForeignKey(blank=True, help_text='Άφησέ το κενό για κατηγορία πρώτου επιπέδου.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category', verbose_name='Γονική κατηγορία')),
            ],
            options={
                'verbose_name': 'Κατηγορία',
                'verbose_name_plural': 'Κατηγορίες',
                'ordering': ['section', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('file', models.FileField(help_text='Επιτρεπτά: pdf, doc, docx, jpg, png. Μέγιστο 25 MB.', storage=content.storage.ProtectedFileSystemStorage(), upload_to=content.storage.uuid_upload_to, validators=[content.validators.validate_upload], verbose_name='Αρχείο')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Αρχικό όνομα')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Τύπος MIME')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Μέγεθος (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία ανεβάσματος')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ορατό')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='content.category', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name': 'Έγγραφο',
                'verbose_name_plural': 'Έγγραφα / Υλικό',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
